In [1]:
import pandas as pd
geo_data = pd.read_parquet("geo_data.parquet")
geo_data

,h3_index,lat,lon,osm_accommodation_closest,osm_accommodation_closest_5_mean,osm_accommodation_count_100,osm_accommodation_count_1000,osm_accommodation_count_2000,osm_accommodation_count_500,osm_adult_closest,...,osm_tourism_hotel_count_100,osm_tourism_hotel_count_1000,osm_tourism_hotel_count_2000,osm_tourism_hotel_count_500,osm_transportation_closest,osm_transportation_closest_5_mean,osm_transportation_count_100,osm_transportation_count_1000,osm_transportation_count_2000,osm_transportation_count_500
0,89013400d37ffff,69.507989,31.316197,NaN,NaN,0,0,0,0,NaN,...,0,0,0,0,5973.238821,6493.004214,0,0,0,0
1,89013404603ffff,69.546583,31.212575,NaN,NaN,0,0,0,0,19908.616467,...,0,0,0,0,60.557823,947.859711,2,2,5,2
2,89013404607ffff,69.548725,31.206807,NaN,NaN,0,0,0,0,19902.769554,...,0,0,0,0,221.920902,925.673931,0,2,5,2
3,8901340460fffff,69.549060,31.214871,NaN,NaN,0,0,0,0,NaN,...,0,0,0,0,105.452756,791.612211,0,2,5,2
4,89013414403ffff,69.422945,31.044869,NaN,NaN,0,0,0,0,8277.769193,...,0,0,0,0,2113.143534,5399.223783,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207517,89316ebab93ffff,42.865151,131.385408,NaN,NaN,0,0,0,0,NaN,...,0,2,3,0,151.795225,239.267794,0,17,49,8
207518,89316ebab9bffff,42.863995,131.382162,NaN,NaN,0,0,0,0,NaN,...,0,2,3,0,194.432781,266.641107,0,11,46,6
207519,89316ebabb3ffff,42.858614,131.390450,NaN,NaN,0,0,0,0,NaN,...,0,1,3,0,0.000000,114.499446,2,21,35,11
207520,89316ebabbbffff,42.857458,131.387205,NaN,NaN,0,0,0,0,NaN,...,0,1,3,0,289.484902,353.823477,0,12,38,7
207521,89316ebacd7ffff,42.904134,131.385675,NaN,NaN,0,0,0,0,NaN,...,0,0,0,0,4908.820529,4949.687143,0,0,0,0

In [2]:
test_data = pd.read_parquet("test.parquet")
test_data

              h3_index industry_type  objects_count
0      892d5035853ffff         other              1
1      89212d8314bffff         other              7
2      8914d641e67ffff         other             57
3      892d49d36a7ffff         other              1
4      892d5e4856bffff         other              6
...                ...           ...            ...
95836  8910814768bffff        apteka              1
95837  8911aa7ad2fffff  stomatologia              2
95838  8911a326277ffff         other              1
95839  890b2218e5bffff     zhivotnye              1
95840  8910a0c6a6bffff         other              1

[95841 rows x 3 columns]

In [3]:
train_data = pd.read_parquet("train.parquet")
train_data

,h3_index,industry_type,transaction_count,customer_count,objects_count,transaction_sum
0,892d4499287ffff,other,7359,3178,11,4526297.17
1,892d292496fffff,other,3692,1564,25,1513250.69
2,8910b14981bffff,napitki_tabak,496,145,1,141914.00
3,8910d9b4a77ffff,beauty_care,273,119,2,406543.00
4,8911060520fffff,other,40980,5567,15,23526497.97
...,...,...,...,...,...,...
287517,89119ec14cbffff,beauty_care,7,6,1,6350.00
287518,8911a8d5907ffff,beauty_care,21,13,1,27066.00
287519,892c604333bffff,apteka,3218,1253,3,1678931.96
287520,89110eb928fffff,other,71,34,2,21026.50
287521,8910e975927ffff,other,2,1,1,176.00

In [4]:
# Объединение обучающих данных с географическими признаками
train_merged = train_data.merge(
    geo_data, 
    on='h3_index',  # ключ объединения - географический индекс
    how='left',     # left join чтобы сохранить все строки из train_data
    suffixes=('', '_geo')
)

# Аналогично для тестовых данных
test_merged = test_data.merge(
    geo_data, 
    on='h3_index', 
    how='left',
    suffixes=('', '_geo')
)

In [5]:
train_merged

,h3_index,industry_type,transaction_count,customer_count,objects_count,transaction_sum,lat,lon,osm_accommodation_closest,osm_accommodation_closest_5_mean,...,osm_tourism_hotel_count_100,osm_tourism_hotel_count_1000,osm_tourism_hotel_count_2000,osm_tourism_hotel_count_500,osm_transportation_closest,osm_transportation_closest_5_mean,osm_transportation_count_100,osm_transportation_count_1000,osm_transportation_count_2000,osm_transportation_count_500
0,892d4499287ffff,other,7359,3178,11,4526297.17,47.216885,38.866084,NaN,NaN,...,0,0,2,0,329.593841,402.572417,0,49,127,14
1,892d292496fffff,other,3692,1564,25,1513250.69,45.421913,35.808481,NaN,NaN,...,0,3,5,1,639.777353,1008.037299,0,2,21,0
2,8910b14981bffff,napitki_tabak,496,145,1,141914.00,51.611589,46.017180,NaN,NaN,...,0,0,0,0,321.697508,377.527784,0,50,136,4
3,8910d9b4a77ffff,beauty_care,273,119,2,406543.00,57.144807,65.546458,NaN,NaN,...,0,3,20,0,21.871035,92.412664,2,272,1099,74
4,8911060520fffff,other,40980,5567,15,23526497.97,59.846357,30.485972,NaN,NaN,...,0,1,3,0,5.003247,75.765146,3,95,264,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287517,89119ec14cbffff,beauty_care,7,6,1,6350.00,51.705821,39.186322,NaN,NaN,...,0,1,6,0,27.207547,90.791138,2,136,347,46
287518,8911a8d5907ffff,beauty_care,21,13,1,27066.00,56.863041,35.877386,NaN,NaN,...,0,1,10,0,3.316391,24.489833,5,54,229,23
287519,892c604333bffff,apteka,3218,1253,3,1678931.96,46.318805,48.020249,NaN,NaN,...,0,0,3,0,14.365905,121.922913,2,17,46,7
287520,89110eb928fffff,other,71,34,2,21026.50,61.817248,34.084848,NaN,NaN,...,0,0,1,0,175.872898,382.984099,0,8,8,3
287521,8910e975927ffff,other,2,1,1,176.00,61.385319,63.577489,NaN,NaN,...,0,0,2,0,389.713750,444.323652,0,10,125,6

In [6]:
from sklearn.cluster import KMeans
import numpy as np

# Создание 200 кластеров на основе координат
k = 200
model = KMeans(n_clusters=k, random_state=42)
train_merged['cluster'] = model.fit_predict(train_merged[['lat', 'lon']])

# Применение той же модели к тестовым данным
test_merged['cluster'] = model.predict(test_merged[['lat', 'lon']])
#train_merged['len_cluster'] = train_merged['cluster'].map(train_merged['cluster'])

#cluster_sizes = train_merged['cluster'].value_counts()

#train_merged['len_cluster'] = train_merged['cluster'].map(cluster_sizes)

In [7]:
test_merged['cluster'] = model.predict(test_merged[['lat', 'lon']])

In [ ]:
# Создание признака - средняя сумма транзакций в кластере
train_df_mean = (
    train_merged.groupby('cluster')['transaction_sum'].mean().reset_index()
    .rename(columns={'transaction_sum': 'kmeans'})
)

In [66]:
# Логарифмирование для нормализации распределения
train_merged['transaction_count'] = train_merged['transaction_count'].apply(lambda x: np.log10(x + 1))
train_merged['customer_count'] = train_merged['customer_count'].apply(lambda x: np.log10(x + 1))
train_merged['transaction_sum'] = train_merged['transaction_sum'].apply(lambda x: np.log10(x + 1))

In [9]:
test_df_mean = (
    train_merged.groupby('cluster')['transaction_sum'].mean().reset_index()
    .rename(columns={'transaction_sum' : 'kmeans'})
)

In [10]:
test_merged = (
    test_merged.merge(
        test_df_mean,
        on = "cluster",
        how = "left"
    )
)

In [11]:
test_merged

,h3_index,industry_type,objects_count,lat,lon,osm_accommodation_closest,osm_accommodation_closest_5_mean,osm_accommodation_count_100,osm_accommodation_count_1000,osm_accommodation_count_2000,...,osm_tourism_hotel_count_2000,osm_tourism_hotel_count_500,osm_transportation_closest,osm_transportation_closest_5_mean,osm_transportation_count_100,osm_transportation_count_1000,osm_transportation_count_2000,osm_transportation_count_500,cluster,kmeans
0,892d5035853ffff,other,1,44.414100,41.510629,NaN,NaN,0,0,0,...,0,0,841.006864,1220.125559,0,2,12,0,154,5.318086
1,89212d8314bffff,other,7,54.448932,61.271869,NaN,NaN,0,0,0,...,2,0,116.510244,233.941411,0,59,86,15,66,5.642783
2,8914d641e67ffff,other,57,48.493462,135.068027,NaN,NaN,0,0,0,...,16,4,18.074244,116.670781,2,52,183,14,28,5.990211
3,892d49d36a7ffff,other,1,49.055930,44.809794,NaN,NaN,0,0,0,...,15,1,605.214260,740.478565,0,4,26,0,25,5.499969
4,892d5e4856bffff,other,6,44.112895,43.489165,NaN,NaN,0,0,0,...,0,0,1234.471366,2133.171461,0,0,2,0,42,5.213887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95836,8910814768bffff,apteka,1,53.206768,50.206302,NaN,NaN,0,0,0,...,7,1,75.877851,96.047036,4,89,445,24,103,5.602300
95837,8911aa7ad2fffff,stomatologia,2,55.788150,37.598684,NaN,NaN,0,0,0,...,34,1,63.788427,115.443795,2,200,853,45,184,6.081322
95838,8911a326277ffff,other,1,55.560329,35.004892,NaN,NaN,0,0,0,...,3,0,56.023355,162.825569,4,61,128,4,181,5.341352
95839,890b2218e5bffff,zhivotnye,1,60.971466,69.040635,NaN,NaN,0,0,0,...,6,1,22.064699,82.609885,5,187,660,35,145,5.589721
95840,8910a0c6a6bffff,other,1,54.298597,44.485888,NaN,NaN,0,0,0,...,1,0,960.340869,987.776113,0,4,31,0,70,5.386159

In [12]:
train_df_mean

     cluster        kmeans
0          0  1.608796e+06
1          1  4.676455e+06
2          2  1.940844e+06
3          3  4.845582e+06
4          4  2.713297e+06
..       ...           ...
195      195  3.827378e+06
196      196  1.177300e+06
197      197  1.257917e+06
198      198  1.256778e+06
199      199  2.270675e+06

[200 rows x 2 columns]

In [13]:
train_merged = (
    train_merged.merge(
        train_df_mean,
        on = "cluster",
        how = "left"
    ).drop(['cluster'], axis = 1)
)

In [14]:
import hdbscan

# HDBSCAN лучше работает с данными сложной формы
clusterer = hdbscan.HDBSCAN(
    min_cluster_size=50,     # минимальный размер кластера
    min_samples=10,          # минимальное количество соседей
    prediction_data=True     # для предсказания на новых данных
)
train_merged['cluster'] = clusterer.fit_predict(train_merged[['lat', 'lon']])

# Размер кластера как важный признак
cluster_sizes = train_merged['cluster'].value_counts()
train_merged['cluster_size'] = train_merged['cluster'].map(cluster_sizes)

/opt/jupyter/lib/python3.12/site-packages/sklearn/utils/deprecation.py:132: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/opt/jupyter/lib/python3.12/site-packages/sklearn/utils/deprecation.py:132: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [15]:
from hdbscan import approximate_predict

# Предсказание кластеров для тестовых данных
test_merged['cluster'], strengths = approximate_predict(clusterer, test_merged[['lat', 'lon']])
cluster_sizes = test_merged['cluster'].value_counts()
test_merged['cluster_size'] = test_merged['cluster'].map(cluster_sizes)

In [16]:
test_merged

,h3_index,industry_type,objects_count,lat,lon,osm_accommodation_closest,osm_accommodation_closest_5_mean,osm_accommodation_count_100,osm_accommodation_count_1000,osm_accommodation_count_2000,...,osm_tourism_hotel_count_500,osm_transportation_closest,osm_transportation_closest_5_mean,osm_transportation_count_100,osm_transportation_count_1000,osm_transportation_count_2000,osm_transportation_count_500,cluster,kmeans,cluster_size
0,892d5035853ffff,other,1,44.414100,41.510629,NaN,NaN,0,0,0,...,0,841.006864,1220.125559,0,2,12,0,566,5.318086,21
1,89212d8314bffff,other,7,54.448932,61.271869,NaN,NaN,0,0,0,...,0,116.510244,233.941411,0,59,86,15,401,5.642783,26
2,8914d641e67ffff,other,57,48.493462,135.068027,NaN,NaN,0,0,0,...,4,18.074244,116.670781,2,52,183,14,93,5.990211,736
3,892d49d36a7ffff,other,1,49.055930,44.809794,NaN,NaN,0,0,0,...,1,605.214260,740.478565,0,4,26,0,-1,5.499969,19023
4,892d5e4856bffff,other,6,44.112895,43.489165,NaN,NaN,0,0,0,...,0,1234.471366,2133.171461,0,0,2,0,343,5.213887,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95836,8910814768bffff,apteka,1,53.206768,50.206302,NaN,NaN,0,0,0,...,1,75.877851,96.047036,4,89,445,24,619,5.602300,828
95837,8911aa7ad2fffff,stomatologia,2,55.788150,37.598684,NaN,NaN,0,0,0,...,1,63.788427,115.443795,2,200,853,45,826,6.081322,2527
95838,8911a326277ffff,other,1,55.560329,35.004892,NaN,NaN,0,0,0,...,0,56.023355,162.825569,4,61,128,4,-1,5.341352,19023
95839,890b2218e5bffff,zhivotnye,1,60.971466,69.040635,NaN,NaN,0,0,0,...,1,22.064699,82.609885,5,187,660,35,52,5.589721,138
95840,8910a0c6a6bffff,other,1,54.298597,44.485888,NaN,NaN,0,0,0,...,0,960.340869,987.776113,0,4,31,0,-1,5.386159,19023

In [17]:
# KeyError: "['kmeans', 'cluster_size', 'HDBSCAN'] not in index"

In [18]:
# Среднее значение транзакций по HDBSCAN кластерам
train_df_mean = (
    train_merged.groupby('cluster')['transaction_sum']
    .mean()
    .reset_index()
    .rename(columns={'transaction_sum': 'HDBSCAN'})
)
# Обработка бесконечных значений
train_df_mean['HDBSCAN'] = train_df_mean['HDBSCAN'].replace([np.inf, -np.inf], np.nan)

   cluster   HDBSCAN
0       -1  5.274793
1        0  5.818663
2        1  5.568076
3        2  5.341170
4        3  5.771717
5        4  5.798140
6        5  5.722065
7        6  6.364616
8        7  6.108065
9        8  5.846344

In [19]:
test_df_mean = (
    train_merged.groupby('cluster')['transaction_sum']
    .mean()
    .reset_index()
    .rename(columns={'transaction_sum': 'HDBSCAN'})
)

# Handle infinite values from empty/noise clusters
test_df_mean['HDBSCAN'] = test_df_mean['HDBSCAN'].replace([np.inf, -np.inf], np.nan)

print(test_df_mean.head(10))

   cluster   HDBSCAN
0       -1  5.274793
1        0  5.818663
2        1  5.568076
3        2  5.341170
4        3  5.771717
5        4  5.798140
6        5  5.722065
7        6  6.364616
8        7  6.108065
9        8  5.846344

In [21]:
train_merged = (
    train_merged.merge(
        train_df_mean,
        on = "cluster",
        how = "left"
    )
)

In [22]:
test_merged = (
    test_merged.merge(
        test_df_mean,
        on = "cluster",
        how = "left"
    )
)

In [23]:
train_df_mean

     cluster   HDBSCAN
1          0  5.818663
2          1  5.568076
3          2  5.341170
4          3  5.771717
5          4  5.798140
..       ...       ...
825      824  6.084657
826      825  5.970664
827      826  6.279992
828      827  6.179124
829      828  6.060586

[829 rows x 2 columns]

In [24]:
test_merged

,h3_index,industry_type,objects_count,lat,lon,osm_accommodation_closest,osm_accommodation_closest_5_mean,osm_accommodation_count_100,osm_accommodation_count_1000,osm_accommodation_count_2000,...,osm_transportation_closest,osm_transportation_closest_5_mean,osm_transportation_count_100,osm_transportation_count_1000,osm_transportation_count_2000,osm_transportation_count_500,cluster,kmeans,cluster_size,HDBSCAN
0,892d5035853ffff,other,1,44.414100,41.510629,NaN,NaN,0,0,0,...,841.006864,1220.125559,0,2,12,0,566,5.318086,21,4.851485
1,89212d8314bffff,other,7,54.448932,61.271869,NaN,NaN,0,0,0,...,116.510244,233.941411,0,59,86,15,401,5.642783,26,5.434817
2,8914d641e67ffff,other,57,48.493462,135.068027,NaN,NaN,0,0,0,...,18.074244,116.670781,2,52,183,14,93,5.990211,736,6.042343
3,892d49d36a7ffff,other,1,49.055930,44.809794,NaN,NaN,0,0,0,...,605.214260,740.478565,0,4,26,0,-1,5.499969,19023,NaN
4,892d5e4856bffff,other,6,44.112895,43.489165,NaN,NaN,0,0,0,...,1234.471366,2133.171461,0,0,2,0,343,5.213887,60,5.356997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95836,8910814768bffff,apteka,1,53.206768,50.206302,NaN,NaN,0,0,0,...,75.877851,96.047036,4,89,445,24,619,5.602300,828,5.686528
95837,8911aa7ad2fffff,stomatologia,2,55.788150,37.598684,NaN,NaN,0,0,0,...,63.788427,115.443795,2,200,853,45,826,6.081322,2527,6.279992
95838,8911a326277ffff,other,1,55.560329,35.004892,NaN,NaN,0,0,0,...,56.023355,162.825569,4,61,128,4,-1,5.341352,19023,NaN
95839,890b2218e5bffff,zhivotnye,1,60.971466,69.040635,NaN,NaN,0,0,0,...,22.064699,82.609885,5,187,660,35,52,5.589721,138,5.606137
95840,8910a0c6a6bffff,other,1,54.298597,44.485888,NaN,NaN,0,0,0,...,960.340869,987.776113,0,4,31,0,-1,5.386159,19023,NaN

In [25]:
# Замена шумовых кластеров средним значением

mean_cluster_train = train_merged.loc[train_merged['cluster'] != -1, 'cluster'].mean()
train_merged['cluster'] = train_merged['cluster'].replace(-1, mean_cluster_train)

mean_cluster_test = test_merged.loc[test_merged['cluster'] != -1, 'cluster'].mean()
test_merged['cluster'] = test_merged['cluster'].replace(-1, mean_cluster_test)

In [26]:
train_merged = train_merged.drop('cluster', axis = 1)
test_merged = test_merged.drop('cluster', axis = 1)

In [27]:
from scipy import stats

def prepare_data(df):
    # Удаление колонок с большим количеством пропусков
    df = df.drop(['osm_accommodation_closest', 'osm_accommodation_closest_5_mean'], axis=1)
    
    for cl in df.columns:
        # Замена бесконечных значений
        df[cl].replace([np.inf, -np.inf], np.nan)
        
        if df[cl].dtype in ['object', 'category']:
            # Для категориальных - мода
            df[cl] = df[cl].fillna(df[cl].mode()[0])
        elif df[cl].dtype in ['int64', 'float64']:
            # Для числовых - медиана
            df[cl] = df[cl].fillna(df[cl].median())
            
            # Удаление выбросов методом z-score
            z = np.abs(stats.zscore(df[cl]))
            median = df[cl].median()
            df.loc[z > 3, cl] = median
    
    return df

# Применение ко всем данным
train_merged = prepare_data(train_merged)
test_merged = prepare_data(test_merged)

/opt/jupyter/lib/python3.12/site-packages/scipy/stats/_stats_py.py:1158: RuntimeWarning: invalid value encountered in subtract
  a_zero_mean = a - mean
/opt/jupyter/lib/python3.12/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/opt/jupyter/lib/python3.12/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/opt/jupyter/lib/python3.12/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/opt/jupyter/lib/python3.12/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/opt/jupyter/lib/python3.12/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/opt/jupyter/lib/python3.12/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/opt/jupyter/lib/python3.12/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/opt/jupyter/lib/python3.12/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

          h3_index  industry_type  transaction_count  customer_count  \
0  892d4499287ffff          other           3.866819        3.502154
1  892d292496fffff          other           3.567262        3.194237
2  8910b14981bffff  napitki_tabak           2.695482        2.161368
3  8910d9b4a77ffff    beauty_care           2.436163        2.075547
4  8911060520fffff          other           4.612572        3.745621

   objects_count  transaction_sum        lat        lon  \
0             11         6.655743  47.216885  38.866084
1             25         6.179911  45.421913  35.808481
2              1         5.152025  51.611589  46.017180
3              2         5.609106  57.144807  65.546458
4             15         7.371557  59.846357  30.485972

   osm_accommodation_count_100  osm_accommodation_count_1000  ...  \
0                            0                             0  ...
1                            0                             0  ...
2                            0                             0  ...
3                            0                             0  ...
4                            0                             0  ...

   osm_tourism_hotel_count_500  osm_transportation_closest  \
0                            0                  329.593841
1                            1                  639.777353
2                            0                  321.697508
3                            0                   21.871035
4                            0                    5.003247

   osm_transportation_closest_5_mean  osm_transportation_count_100  \
0                         402.572417                             0
1                        1008.037299                             0
2                         377.527784                             0
3                          92.412664                             2
4                          75.765146                             3

   osm_transportation_count_1000  osm_transportation_count_2000  \
0                             49                            127
1                              2                             21
2                             50                            136
3                            272                            122
4                             95                            264

   osm_transportation_count_500        kmeans  cluster_size   HDBSCAN
0                            14  1.246834e+06           882  5.448923
1                             0  6.636579e+05            64  5.692034
2                             4  2.346394e+06          1873  5.615027
3                            74  5.538901e+06          2843  5.900189
4                            23  6.744086e+06            89  6.056601

[5 rows x 345 columns]
--------------------------------------------------

/opt/jupyter/lib/python3.12/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/opt/jupyter/lib/python3.12/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/opt/jupyter/lib/python3.12/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/opt/jupyter/lib/python3.12/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

          h3_index industry_type  objects_count        lat        lon  \
0  892d5035853ffff         other              1  44.414100  41.510629
1  89212d8314bffff         other              7  54.448932  61.271869
2  8914d641e67ffff         other             57  48.493462  43.870574
3  892d49d36a7ffff         other              1  49.055930  44.809794
4  892d5e4856bffff         other              6  44.112895  43.489165

   osm_accommodation_count_100  osm_accommodation_count_1000  \
0                            0                             0
1                            0                             0
2                            0                             0
3                            0                             0
4                            0                             0

   osm_accommodation_count_2000  osm_accommodation_count_500  \
0                             0                            0
1                             0                            0
2                             0                            0
3                             0                            0
4                             0                            0

   osm_adult_closest  ...  osm_tourism_hotel_count_500  \
0        2610.329349  ...                            0
1         941.529917  ...                            0
2        1565.691066  ...                            4
3        2610.329349  ...                            1
4        2610.329349  ...                            0

   osm_transportation_closest  osm_transportation_closest_5_mean  \
0                  841.006864                        1220.125559
1                  116.510244                         233.941411
2                   18.074244                         116.670781
3                  605.214260                         740.478565
4                 1234.471366                        2133.171461

   osm_transportation_count_100  osm_transportation_count_1000  \
0                             0                              2
1                             0                             59
2                             2                             52
3                             0                              4
4                             0                              0

   osm_transportation_count_2000  osm_transportation_count_500    kmeans  \
0                             12                             0  5.318086
1                             86                            15  5.642783
2                            183                            14  5.990211
3                             26                             0  5.499969
4                              2                             0  5.213887

   cluster_size   HDBSCAN
0            21  4.851485
1            26  5.434817
2           736  6.042343
3         19023  5.687729
4            60  5.356997

[5 rows x 342 columns]
--------------------------------------------------

/opt/jupyter/lib/python3.12/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/opt/jupyter/lib/python3.12/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/opt/jupyter/lib/python3.12/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/opt/jupyter/lib/python3.12/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [28]:
# for i in X_train_sel.columns:
#     if np.isinf(X_train_sel[i]).any():
#         print(f"{i}")
# print(np.isinf(X_train_sel['customer_count_knn']).sum())

In [29]:
train_merged['industry_type'].value_counts()

industry_type
other                  152624
kafe_delivery           27098
napitki_tabak           16576
apteka                  15256
clothes                 11172
beauty_care             10097
medicina                 9271
avtozapchasti            7828
zhivotnye                6199
elektronika_tehnika      5773
stomatologia             5616
avtoservis               5054
kosmetika_parfum         4963
detskie_tovary           4648
yuvelirny                2591
fitnes                   2292
kompjuterny_remont        464
Name: count, dtype: int64

In [30]:
train_merged = train_merged.drop(drop_cols, axis = 1)

test_merged = test_merged.drop(drop_cols, axis = 1)

In [31]:
train_merged = train_merged.drop("transaction_count", axis = 1)

In [32]:
from sklearn.neighbors import NearestNeighbors

# Поиск 5 ближайших соседей по координатам
knn = NearestNeighbors(n_neighbors=5, algorithm='ball_tree', metric='haversine')
knn.fit(np.radians(train_merged[['lat', 'lon']]).to_numpy())

# Предсказание для обучающих данных
distances_train, indices_train = knn.kneighbors(np.radians(train_merged[['lat', 'lon']]).to_numpy())

# Создание признака - среднее количество клиентов у ближайших соседей
customer_count_train_pred = [
    train_merged.iloc[idx[1:]]['customer_count'].mean()  # [1:] чтобы исключить саму точку
    for idx in indices_train
]
train_merged['customer_count_knn'] = customer_count_train_pred

start NearestNeighbors
start fit NearestNeighbors
end fit NearestNeighbors

In [33]:

print("distances_datas ")

customer_count_train_pred = [
    train_merged.iloc[idx[1:]]['customer_count'].mean()
    for idx in indices_train
]
print("End data_train")
train_merged['customer_count_knn'] = customer_count_train_pred

distances_datas
End data_train

/tmp/ipykernel_565547/1236793606.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_merged['customer_count_knn'] = customer_count_train_pred

In [34]:
customer_count_test_pred = [
    train_merged.iloc[idx[1:]]['customer_count'].mean()
    for idx in indices_test
]
print("End")

test_merged['customer_count_knn'] = customer_count_test_pred

End

/tmp/ipykernel_565547/3929396586.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_merged['customer_count_knn'] = customer_count_test_pred

In [35]:
test_merged.groupby("industry_type").first()

,h3_index,objects_count,lat,lon,osm_accommodation_count_100,osm_accommodation_count_1000,osm_accommodation_count_2000,osm_accommodation_count_500,osm_adult_closest,osm_adult_closest_5_mean,...,osm_transportation_closest,osm_transportation_closest_5_mean,osm_transportation_count_100,osm_transportation_count_1000,osm_transportation_count_2000,osm_transportation_count_500,kmeans,cluster_size,HDBSCAN,customer_count_knn
industry_type,,,,,,,,,,,,,,,,,,,,,
apteka,892d440e823ffff,2,47.247400,39.712383,0,0,0,0,96.326108,1758.035946,...,24.958890,69.598268,4,56,205,15,5.444257,1003,5.604693,3.237004
avtoservis,8911061484bffff,1,59.941813,30.261139,0,0,0,0,864.823056,1339.012505,...,95.628084,163.432508,1,96,631,29,5.940880,1197,6.133813,2.257335
avtozapchasti,8910d149293ffff,1,55.111892,59.706971,0,0,0,0,2610.329349,4418.355591,...,100.395681,126.336232,0,104,154,36,5.422934,39,5.513289,1.440467
beauty_care,8911aa790cfffff,2,55.641872,37.602893,0,0,0,0,2636.739955,5354.234318,...,1.136709,54.413820,4,182,481,58,6.081322,2527,6.279992,3.007879
clothes,8910d9b4ac7ffff,3,57.147670,65.524825,0,0,0,0,1357.038874,1993.483123,...,75.605031,88.736057,4,218,721,45,5.807748,928,5.900189,2.840281
detskie_tovary,890b9a74c27ffff,1,56.041188,92.904504,0,0,0,0,810.269660,3166.160923,...,25.817724,40.770494,6,279,844,70,5.733033,653,5.876100,2.679489
elektronika_tehnika,8910ac15e07ffff,3,56.114343,47.488994,0,0,0,0,1191.884500,10378.313105,...,47.586189,180.655824,1,44,182,10,5.518059,82,5.474941,2.325079
fitnes,8911aa7aa43ffff,1,55.735079,37.611363,0,0,0,0,424.986061,565.837206,...,144.713977,213.331119,0,205,882,40,6.081322,2527,6.279992,2.704897
kafe_delivery,891106066b3ffff,14,59.924681,30.322963,0,0,0,0,280.079111,484.545909,...,35.892302,70.878500,4,97,505,32,5.940880,1197,6.133813,2.132528
kompjuterny_remont,891106a959bffff,1,60.008176,30.297619,0,0,0,0,1652.450101,1864.778953,...,24.698624,33.569991,5,160,644,48,5.940880,1197,6.133813,2.973971
kosmetika_parfum,8910b3844b7ffff,6,51.509585,45.975883,0,0,0,0,3616.871791,4266.310579,...,29.514894,127.798710,2,24,67,9,5.529702,610,5.615027,3.313335
medicina,8911aa68e73ffff,11,55.703187,37.920112,0,0,0,0,2561.355082,5139.016777,...,29.520211,80.238267,3,152,605,22,5.839280,278,5.966959,3.256436
napitki_tabak,89110614eabffff,4,59.938689,30.236760,0,0,0,0,1121.269716,1440.465156,...,103.987804,201.541111,0,179,688,31,5.940880,1197,6.133813,0.946154
other,892d5035853ffff,1,44.414100,41.510629,0,0,0,0,2610.329349,4418.355591,...,841.006864,1220.125559,0,2,12,0,5.318086,21,4.851485,1.758438
stomatologia,892c29d8003ffff,1,43.028142,44.677675,0,0,0,0,693.418763,2243.627817,...,260.250974,315.347411,0,30,170,8,5.227675,224,5.556162,2.358824
yuvelirny,891188b1447ffff,1,56.131713,40.418929,0,0,0,0,631.673144,1560.168202,...,67.472466,77.895042,8,133,417,61,5.625605,222,5.808848,3.293330
zhivotnye,890b9a74933ffff,2,56.062728,92.949108,0,0,0,0,3719.862850,6838.848297,...,4.624495,51.390893,4,149,392,37,5.733033,653,5.876100,2.605537

In [36]:
def transaction(data, n_neighbours, is_train=True):
    df = data.copy()
    df['transaction_sum_knn'] = np.nan
    
    # Разные KNN модели для каждого типа бизнеса
    groups = df.groupby("industry_type")
    base_df = train_merged if not is_train else df
    
    for industry_type, group in groups:
        knn = NearestNeighbors(n_neighbors=n_neighbours, algorithm='ball_tree', metric='haversine')
        knn.fit(np.radians(base_df.loc[base_df['industry_type'] == industry_type, ['lat', 'lon']].to_numpy()))
        
        distances, indices = knn.kneighbors(np.radians(group[['lat', 'lon']]).to_numpy())
        
        # Для обучающих данных исключаем саму точку, для тестовых - нет
        first_idx = 1 if is_train else 0       
        transaction_sum_pred = [
            base_df.iloc[idx[first_idx:]]['customer_count'].mean()
            for idx in indices
        ]
        df.loc[group.index, 'transaction_sum_knn'] = transaction_sum_pred
    
    return df

# Создание признаков
train_merged = transaction(train_merged, n_neighbours=5, is_train=True)
test_merged = transaction(test_merged, n_neighbours=5, is_train=False)

start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
          h3_index  industry_type  customer_count  objects_count  \
0  892d4499287ffff          other        3.502154             11
1  892d292496fffff          other        3.194237             25
2  8910b14981bffff  napitki_tabak        2.161368              1
3  8910d9b4a77ffff    beauty_care        2.075547              2
4  8911060520fffff          other        3.745621             15

   transaction_sum        lat        lon  osm_accommodation_count_100  \
0         6.655743  47.216885  38.866084                            0
1         6.179911  45.421913  35.808481                            0
2         5.152025  51.611589  46.017180                            0
3         5.609106  57.144807  65.546458                            0
4         7.371557  59.846357  30.485972                            0

   osm_accommodation_count_1000  osm_accommodation_count_2000  ...  \
0                             0                             0  ...
1                             0                             0  ...
2                             0                             0  ...
3                             0                             0  ...
4                             0                             0  ...

   osm_transportation_closest_5_mean  osm_transportation_count_100  \
0                         402.572417                             0
1                        1008.037299                             0
2                         377.527784                             0
3                          92.412664                             2
4                          75.765146                             3

   osm_transportation_count_1000  osm_transportation_count_2000  \
0                             49                            127
1                              2                             21
2                             50                            136
3                            272                            122
4                             95                            264

   osm_transportation_count_500        kmeans  cluster_size   HDBSCAN  \
0                            14  1.246834e+06           882  5.448923
1                             0  6.636579e+05            64  5.692034
2                             4  2.346394e+06          1873  5.615027
3                            74  5.538901e+06          2843  5.900189
4                            23  6.744086e+06            89  6.056601

   customer_count_knn  transaction_sum_knn
0            3.035923             1.807738
1            2.153429             2.571689
2            2.511053             2.110673
3            2.502803             1.859932
4            2.610430             2.369383

[5 rows x 342 columns]
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
          h3_index industry_type  objects_count        lat        lon  \
0  892d5035853ffff         other              1  44.414100  41.510629
1  89212d8314bffff         other              7  54.448932  61.271869
2  8914d641e67ffff         other             57  48.493462  43.870574
3  892d49d36a7ffff         other              1  49.055930  44.809794
4  892d5e4856bffff         other              6  44.112895  43.489165

   osm_accommodation_count_100  osm_accommodation_count_1000  \
0                            0                             0
1                            0                             0
2                            0                             0
3                            0                             0
4                            0                             0

   osm_accommodation_count_2000  osm_accommodation_count_500  \
0                             0                            0
1                             0                            0
2                             0                            0
3                             0                            0
4                             0                            0

   osm_adult_closest  ...  osm_transportation_closest_5_mean  \
0        2610.329349  ...                        1220.125559
1         941.529917  ...                         233.941411
2        1565.691066  ...                         116.670781
3        2610.329349  ...                         740.478565
4        2610.329349  ...                        2133.171461

   osm_transportation_count_100  osm_transportation_count_1000  \
0                             0                              2
1                             0                             59
2                             2                             52
3                             0                              4
4                             0                              0

   osm_transportation_count_2000  osm_transportation_count_500    kmeans  \
0                             12                             0  5.318086
1                             86                            15  5.642783
2                            183                            14  5.990211
3                             26                             0  5.499969
4                              2                             0  5.213887

   cluster_size   HDBSCAN  customer_count_knn  transaction_sum_knn
0            21  4.851485            1.758438             1.959707
1            26  5.434817            3.188032             2.683446
2           736  6.042343            2.202113             1.885091
3         19023  5.687729            2.137115             2.471634
4            60  5.356997            1.678341             2.026792

[5 rows x 340 columns]

In [37]:
transaction(train_merged, n_neighbours = 5, is_train = True)

start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
start fit NearestNeighbors
start pred transaction_sum_pred
          h3_index  industry_type  customer_count  objects_count  \
0  892d4499287ffff          other        3.502154             11
1  892d292496fffff          other        3.194237             25
2  8910b14981bffff  napitki_tabak        2.161368              1
3  8910d9b4a77ffff    beauty_care        2.075547              2
4  8911060520fffff          other        3.745621             15

   transaction_sum        lat        lon  osm_accommodation_count_100  \
0         6.655743  47.216885  38.866084                            0
1         6.179911  45.421913  35.808481                            0
2         5.152025  51.611589  46.017180                            0
3         5.609106  57.144807  65.546458                            0
4         7.371557  59.846357  30.485972                            0

   osm_accommodation_count_1000  osm_accommodation_count_2000  ...  \
0                             0                             0  ...
1                             0                             0  ...
2                             0                             0  ...
3                             0                             0  ...
4                             0                             0  ...

   osm_transportation_closest_5_mean  osm_transportation_count_100  \
0                         402.572417                             0
1                        1008.037299                             0
2                         377.527784                             0
3                          92.412664                             2
4                          75.765146                             3

   osm_transportation_count_1000  osm_transportation_count_2000  \
0                             49                            127
1                              2                             21
2                             50                            136
3                            272                            122
4                             95                            264

   osm_transportation_count_500        kmeans  cluster_size   HDBSCAN  \
0                            14  1.246834e+06           882  5.448923
1                             0  6.636579e+05            64  5.692034
2                             4  2.346394e+06          1873  5.615027
3                            74  5.538901e+06          2843  5.900189
4                            23  6.744086e+06            89  6.056601

   customer_count_knn  transaction_sum_knn
0            3.035923             1.807738
1            2.153429             2.571689
2            2.511053             2.110673
3            2.502803             1.859932
4            2.610430             2.369383

[5 rows x 342 columns]

,h3_index,industry_type,customer_count,objects_count,transaction_sum,lat,lon,osm_accommodation_count_100,osm_accommodation_count_1000,osm_accommodation_count_2000,...,osm_transportation_closest_5_mean,osm_transportation_count_100,osm_transportation_count_1000,osm_transportation_count_2000,osm_transportation_count_500,kmeans,cluster_size,HDBSCAN,customer_count_knn,transaction_sum_knn
0,892d4499287ffff,other,3.502154,11,6.655743,47.216885,38.866084,0,0,0,...,402.572417,0,49,127,14,1.246834e+06,882,5.448923,3.035923,1.807738
1,892d292496fffff,other,3.194237,25,6.179911,45.421913,35.808481,0,0,0,...,1008.037299,0,2,21,0,6.636579e+05,64,5.692034,2.153429,2.571689
2,8910b14981bffff,napitki_tabak,2.161368,1,5.152025,51.611589,46.017180,0,0,0,...,377.527784,0,50,136,4,2.346394e+06,1873,5.615027,2.511053,2.110673
3,8910d9b4a77ffff,beauty_care,2.075547,2,5.609106,57.144807,65.546458,0,0,0,...,92.412664,2,272,122,74,5.538901e+06,2843,5.900189,2.502803,1.859932
4,8911060520fffff,other,3.745621,15,7.371557,59.846357,30.485972,0,0,0,...,75.765146,3,95,264,23,6.744086e+06,89,6.056601,2.610430,2.369383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287517,89119ec14cbffff,beauty_care,0.778151,1,3.802774,51.705821,39.186322,0,0,0,...,90.791138,2,136,347,46,2.766745e+06,1870,5.640293,1.702803,2.518450
287518,8911a8d5907ffff,beauty_care,1.113943,1,4.432424,56.863041,35.877386,0,0,0,...,24.489833,5,54,229,23,3.480707e+06,1408,5.732075,1.578216,1.840788
287519,892c604333bffff,apteka,3.097951,3,6.225033,46.318805,48.020249,0,0,0,...,121.922913,2,17,46,7,1.608796e+06,1657,5.378774,2.421871,1.953182
287520,89110eb928fffff,other,1.531479,2,4.322767,61.817248,34.084848,0,0,0,...,382.984099,0,8,8,3,4.825535e+06,53236,5.692034,2.575408,1.671537
287521,8910e975927ffff,other,0.000000,1,5.670791,61.385319,63.577489,0,0,0,...,444.323652,0,10,125,6,1.256778e+06,123,5.329302,2.116375,2.130529

In [38]:
# for i in train_merged.columns:
#     if np.isinf(train_merged[i]).any():
#         print(f"{i}")
# print(np.isinf(train_merged['customer_count_knn']).sum())

In [39]:
train_merged

,h3_index,industry_type,customer_count,objects_count,transaction_sum,lat,lon,osm_accommodation_count_100,osm_accommodation_count_1000,osm_accommodation_count_2000,...,osm_transportation_closest_5_mean,osm_transportation_count_100,osm_transportation_count_1000,osm_transportation_count_2000,osm_transportation_count_500,kmeans,cluster_size,HDBSCAN,customer_count_knn,transaction_sum_knn
0,892d4499287ffff,other,3.502154,11,6.655743,47.216885,38.866084,0,0,0,...,402.572417,0,49,127,14,1.246834e+06,882,5.448923,3.035923,1.807738
1,892d292496fffff,other,3.194237,25,6.179911,45.421913,35.808481,0,0,0,...,1008.037299,0,2,21,0,6.636579e+05,64,5.692034,2.153429,2.571689
2,8910b14981bffff,napitki_tabak,2.161368,1,5.152025,51.611589,46.017180,0,0,0,...,377.527784,0,50,136,4,2.346394e+06,1873,5.615027,2.511053,2.110673
3,8910d9b4a77ffff,beauty_care,2.075547,2,5.609106,57.144807,65.546458,0,0,0,...,92.412664,2,272,122,74,5.538901e+06,2843,5.900189,2.502803,1.859932
4,8911060520fffff,other,3.745621,15,7.371557,59.846357,30.485972,0,0,0,...,75.765146,3,95,264,23,6.744086e+06,89,6.056601,2.610430,2.369383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287517,89119ec14cbffff,beauty_care,0.778151,1,3.802774,51.705821,39.186322,0,0,0,...,90.791138,2,136,347,46,2.766745e+06,1870,5.640293,1.702803,2.518450
287518,8911a8d5907ffff,beauty_care,1.113943,1,4.432424,56.863041,35.877386,0,0,0,...,24.489833,5,54,229,23,3.480707e+06,1408,5.732075,1.578216,1.840788
287519,892c604333bffff,apteka,3.097951,3,6.225033,46.318805,48.020249,0,0,0,...,121.922913,2,17,46,7,1.608796e+06,1657,5.378774,2.421871,1.953182
287520,89110eb928fffff,other,1.531479,2,4.322767,61.817248,34.084848,0,0,0,...,382.984099,0,8,8,3,4.825535e+06,53236,5.692034,2.575408,1.671537
287521,8910e975927ffff,other,0.000000,1,5.670791,61.385319,63.577489,0,0,0,...,444.323652,0,10,125,6,1.256778e+06,123,5.329302,2.116375,2.130529

In [40]:
from sklearn.preprocessing import OrdinalEncoder
from lightgbm import LGBMRegressor
from boruta import BorutaPy
cols_inf = ['customer_count_knn', 'transaction_sum_knn']
train_merged[cols_inf] = train_merged[cols_inf].replace([np.inf], 1)
train_merged[cols_inf] = train_merged[cols_inf].replace([-np.inf], -1)

encoder = OrdinalEncoder()
X_train_sel = train_merged.copy().drop(['h3_index', 'transaction_sum', 'customer_count'], axis = 1)
X_train_sel['industry_type'] = encoder.fit_transform(X_train_sel[['industry_type']])
X_train_sel = X_train_sel.fillna(0.0)
y_train_sel = train_merged['transaction_sum']

model_sel = LGBMRegressor(force_row_size = True, verbose = -1, random_state=42)

selector = BorutaPy(model_sel, verbose = 2)
selector.fit(X_train_sel, y_train_sel)

Iteration: 	1 / 100
Confirmed: 	0
Tentative: 	339
Rejected: 	0
Iteration: 	2 / 100
Confirmed: 	0
Tentative: 	339
Rejected: 	0
Iteration: 	3 / 100
Confirmed: 	0
Tentative: 	339
Rejected: 	0
Iteration: 	4 / 100
Confirmed: 	0
Tentative: 	339
Rejected: 	0
Iteration: 	5 / 100
Confirmed: 	0
Tentative: 	339
Rejected: 	0
Iteration: 	6 / 100
Confirmed: 	0
Tentative: 	339
Rejected: 	0
Iteration: 	7 / 100
Confirmed: 	0
Tentative: 	339
Rejected: 	0
Iteration: 	8 / 100
Confirmed: 	0
Tentative: 	18
Rejected: 	321
Iteration: 	9 / 100
Confirmed: 	4
Tentative: 	14
Rejected: 	321
Iteration: 	10 / 100
Confirmed: 	4
Tentative: 	14
Rejected: 	321
Iteration: 	11 / 100
Confirmed: 	4
Tentative: 	14
Rejected: 	321
Iteration: 	12 / 100
Confirmed: 	4
Tentative: 	10
Rejected: 	325
Iteration: 	13 / 100
Confirmed: 	4
Tentative: 	10
Rejected: 	325
Iteration: 	14 / 100
Confirmed: 	4
Tentative: 	10
Rejected: 	325
Iteration: 	15 / 100
Confirmed: 	4
Tentative: 	10
Rejected: 	325
Iteration: 	16 / 100
Confirmed: 	4
Tentative: 	10
Rejected: 	325
Iteration: 	17 / 100
Confirmed: 	4
Tentative: 	10
Rejected: 	325
Iteration: 	18 / 100
Confirmed: 	4
Tentative: 	10
Rejected: 	325
Iteration: 	19 / 100
Confirmed: 	4
Tentative: 	10
Rejected: 	325
Iteration: 	20 / 100
Confirmed: 	4
Tentative: 	10
Rejected: 	325
Iteration: 	21 / 100
Confirmed: 	4
Tentative: 	10
Rejected: 	325
Iteration: 	22 / 100
Confirmed: 	5
Tentative: 	9
Rejected: 	325
Iteration: 	23 / 100
Confirmed: 	5
Tentative: 	9
Rejected: 	325
Iteration: 	24 / 100
Confirmed: 	5
Tentative: 	9
Rejected: 	325
Iteration: 	25 / 100
Confirmed: 	5
Tentative: 	9
Rejected: 	325
Iteration: 	26 / 100
Confirmed: 	6
Tentative: 	8
Rejected: 	325
Iteration: 	27 / 100
Confirmed: 	6
Tentative: 	8
Rejected: 	325
Iteration: 	28 / 100
Confirmed: 	6
Tentative: 	8
Rejected: 	325
Iteration: 	29 / 100
Confirmed: 	7
Tentative: 	6
Rejected: 	326
Iteration: 	30 / 100
Confirmed: 	7
Tentative: 	6
Rejected: 	326
Iteration: 	31 / 100
Confirmed: 	7
Tentative: 	6
Rejected: 	326
Iteration: 	32 / 100
Confirmed: 	7
Tentative: 	6
Rejected: 	326
Iteration: 	33 / 100
Confirmed: 	7
Tentative: 	6
Rejected: 	326
Iteration: 	34 / 100
Confirmed: 	7
Tentative: 	3
Rejected: 	329
Iteration: 	35 / 100
Confirmed: 	7
Tentative: 	3
Rejected: 	329
Iteration: 	36 / 100
Confirmed: 	7
Tentative: 	3
Rejected: 	329
Iteration: 	37 / 100
Confirmed: 	7
Tentative: 	3
Rejected: 	329
Iteration: 	38 / 100
Confirmed: 	7
Tentative: 	3
Rejected: 	329
Iteration: 	39 / 100
Confirmed: 	7
Tentative: 	3
Rejected: 	329
Iteration: 	40 / 100
Confirmed: 	7
Tentative: 	3
Rejected: 	329
Iteration: 	41 / 100
Confirmed: 	7
Tentative: 	3
Rejected: 	329
Iteration: 	42 / 100
Confirmed: 	7
Tentative: 	3
Rejected: 	329
Iteration: 	43 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	44 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	45 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	46 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	47 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	48 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	49 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	50 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	51 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	52 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	53 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	54 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	55 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	56 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	57 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	58 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	59 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	60 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	61 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	62 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	63 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	64 / 100
Confirmed: 	9
Tentative: 	1
Rejected: 	329
Iteration: 	65 / 100
Confirmed: 	10
Tentative: 	0
Rejected: 	329


BorutaPy finished running.

Iteration: 	66 / 100
Confirmed: 	10
Tentative: 	0
Rejected: 	329

BorutaPy(estimator=LGBMRegressor(force_row_size=True, n_estimators=1000,
                                 random_state=5286, verbose=-1),
         random_state=RandomState(MT19937) at 0x7FBE60BEB640, verbose=2)

In [138]:
train_merged['customer_count_knn']

0         3.035923
1         2.153429
2         2.511053
3         2.502803
4         2.610430
            ...
287517    1.702803
287518    1.578216
287519    2.421871
287520    2.575408
287521    2.116375
Name: customer_count_knn, Length: 287522, dtype: float64

In [42]:
selected_cols = X_train_sel.columns[selector.ranking_ <= np.median(selector.ranking_)]
print(f'{len(selected_cols)} features selected, among which most important are: /n'
     f'{X_train_sel.columns[selector.ranking_ == 1].tolist()}')

170 features selected, among which most important are: /n['industry_type', 'lat', 'lon', 'osm_amenity_fuel_closest', 'osm_auto_roads_closest', 'osm_healthcare_closest', 'osm_leisure_stadium_closest_5_mean', 'osm_residential_closest_5_mean', 'osm_shop_supermarket_closest', 'customer_count_knn']

In [43]:
test_merged

,h3_index,industry_type,objects_count,lat,lon,osm_accommodation_count_100,osm_accommodation_count_1000,osm_accommodation_count_2000,osm_accommodation_count_500,osm_adult_closest,...,osm_transportation_closest_5_mean,osm_transportation_count_100,osm_transportation_count_1000,osm_transportation_count_2000,osm_transportation_count_500,kmeans,cluster_size,HDBSCAN,customer_count_knn,transaction_sum_knn
0,892d5035853ffff,other,1,44.414100,41.510629,0,0,0,0,2610.329349,...,1220.125559,0,2,12,0,5.318086,21,4.851485,1.758438,1.959707
1,89212d8314bffff,other,7,54.448932,61.271869,0,0,0,0,941.529917,...,233.941411,0,59,86,15,5.642783,26,5.434817,3.188032,2.683446
2,8914d641e67ffff,other,57,48.493462,43.870574,0,0,0,0,1565.691066,...,116.670781,2,52,183,14,5.990211,736,6.042343,2.202113,1.885091
3,892d49d36a7ffff,other,1,49.055930,44.809794,0,0,0,0,2610.329349,...,740.478565,0,4,26,0,5.499969,19023,5.687729,2.137115,2.471634
4,892d5e4856bffff,other,6,44.112895,43.489165,0,0,0,0,2610.329349,...,2133.171461,0,0,2,0,5.213887,60,5.356997,1.678341,2.026792
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95836,8910814768bffff,apteka,1,53.206768,50.206302,0,0,0,0,2237.245485,...,96.047036,4,89,445,24,5.602300,828,5.686528,1.753189,2.318662
95837,8911aa7ad2fffff,stomatologia,2,55.788150,37.598684,0,0,0,0,559.787170,...,115.443795,2,200,853,45,6.081322,2527,6.279992,1.990817,1.851101
95838,8911a326277ffff,other,1,55.560329,35.004892,0,0,0,0,2610.329349,...,162.825569,4,61,128,4,5.341352,19023,5.687729,2.612702,2.324957
95839,890b2218e5bffff,zhivotnye,1,60.971466,69.040635,0,0,0,0,877.944674,...,82.609885,5,187,660,35,5.589721,138,5.606137,2.845088,2.613758
95840,8910a0c6a6bffff,other,1,54.298597,44.485888,0,0,0,0,2610.329349,...,987.776113,0,4,31,0,5.386159,19023,5.687729,2.646655,2.498830

In [132]:
from sklearn.model_selection import train_test_split
import pandas as pd
transaction_sum = pd.read_parquet("train.parquet")['transaction_sum'].apply(lambda x : np.log10(x + 1))

train_merged['industry_type'] = train_merged['industry_type'].astype('category')
test_merged['industry_type'] = test_merged['industry_type'].astype('category')

X = train_merged[selected_cols]
y = transaction_sum

In [133]:
selected_cols

Index(['industry_type', 'objects_count', 'lat', 'lon', 'osm_adult_closest',
       'osm_adult_closest_5_mean', 'osm_amenity_bank_closest',
       'osm_amenity_bank_closest_5_mean', 'osm_amenity_bus_station_closest',
       'osm_amenity_bus_station_closest_5_mean',
       ...
       'osm_transportation_closest', 'osm_transportation_closest_5_mean',
       'osm_transportation_count_1000', 'osm_transportation_count_2000',
       'osm_transportation_count_500', 'kmeans', 'cluster_size', 'HDBSCAN',
       'customer_count_knn', 'transaction_sum_knn'],
      dtype='object', length=170)

In [134]:

# for cl in train_merged.columns:
#     if (train_merged[cl].isna().sum() + list(train_merged[cl]).count("-inf") > 0) :
#         print(f"Columns: {cl} nans and -inf - {train_merged[cl].isna().sum() + list(train_merged[cl]).count("-inf")}, - inf {list(train_merged[cl]).count("-inf")}, nans : {train_merged[cl].isna().sum()}")
#     # else:
#     #     print("OWOWOWOWOW")

In [135]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from math import sqrt


X_train, X_valid, y_train, y_valid = train_test_split(
    X, y, test_size=0.1, random_state=42, stratify=train_merged['industry_type']
)

X_train, X_test, y_train, y_test = train_test_split(
    X_train, y_train, test_size=0.4, random_state=42, stratify=X_train['industry_type']
)

In [48]:
import optuna
import lightgbm as lgb
import numpy as np
import pandas as pd
def objective(trial):
    params = {
        'objective': 'regression',
        'metric': 'mae',
        'boosting_type': 'gbdt',
        'verbosity': -1,
        'seed': 42,
        'num_leaves': trial.suggest_int('num_leaves', 20, 128),
        'max_depth': trial.suggest_int('max_depth', 3, 12),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
        'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 20, 100),
        'feature_fraction': trial.suggest_float('feature_fraction', 0.6, 1.0),
        'bagging_fraction': trial.suggest_float('bagging_fraction', 0.6, 1.0),
        'bagging_freq': trial.suggest_int('bagging_freq', 1, 5)
    } 
    model = LGBMRegressor(**params)
    model.fit(
        X_train, y_train,
        eval_set = [(X_valid, y_valid)]
    )
    preds = model.predict(X_valid)
    MAE = mean_absolute_error(y_valid, preds)
    return MAE

study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=100)
#Выполняем подбор параметров при помощи optuna к LGBMRegressor.

[I 2025-11-08 23:08:07,494] A new study created in memory with name: no-name-87d8fc3e-923b-4e07-a3cf-fd334c7538b8
[I 2025-11-08 23:08:09,297] Trial 0 finished with value: 0.5272912459077056 and parameters: {'num_leaves': 84, 'max_depth': 4, 'learning_rate': 0.02517988092038851, 'min_data_in_leaf': 100, 'feature_fraction': 0.8766114365873776, 'bagging_fraction': 0.9021641513629944, 'bagging_freq': 4}. Best is trial 0 with value: 0.5272912459077056.
[I 2025-11-08 23:08:11,020] Trial 1 finished with value: 0.5345153321624314 and parameters: {'num_leaves': 58, 'max_depth': 5, 'learning_rate': 0.022648818815593986, 'min_data_in_leaf': 24, 'feature_fraction': 0.6243910531149756, 'bagging_fraction': 0.7244738349195617, 'bagging_freq': 2}. Best is trial 0 with value: 0.5272912459077056.
[I 2025-11-08 23:08:12,563] Trial 2 finished with value: 0.505808335335007 and parameters: {'num_leaves': 43, 'max_depth': 4, 'learning_rate': 0.1570661406100693, 'min_data_in_leaf': 54, 'feature_fraction': 0.6998999296467173, 'bagging_fraction': 0.7463214736794874, 'bagging_freq': 4}. Best is trial 2 with value: 0.505808335335007.
[I 2025-11-08 23:08:14,098] Trial 3 finished with value: 0.5114558159205649 and parameters: {'num_leaves': 38, 'max_depth': 4, 'learning_rate': 0.0607766470151514, 'min_data_in_leaf': 27, 'feature_fraction': 0.6310115402797299, 'bagging_fraction': 0.6972798949093466, 'bagging_freq': 3}. Best is trial 2 with value: 0.505808335335007.
[I 2025-11-08 23:08:17,071] Trial 4 finished with value: 0.5036924646316475 and parameters: {'num_leaves': 117, 'max_depth': 12, 'learning_rate': 0.040580836584568486, 'min_data_in_leaf': 41, 'feature_fraction': 0.9848447978578434, 'bagging_fraction': 0.8825457669221846, 'bagging_freq': 3}. Best is trial 4 with value: 0.5036924646316475.
[I 2025-11-08 23:08:19,882] Trial 5 finished with value: 0.5102944911462932 and parameters: {'num_leaves': 109, 'max_depth': 9, 'learning_rate': 0.02654863878981606, 'min_data_in_leaf': 93, 'feature_fraction': 0.8634397680793484, 'bagging_fraction': 0.9317868042867755, 'bagging_freq': 1}. Best is trial 4 with value: 0.5036924646316475.
[I 2025-11-08 23:08:21,736] Trial 6 finished with value: 0.5024347083825557 and parameters: {'num_leaves': 31, 'max_depth': 10, 'learning_rate': 0.1549685330966436, 'min_data_in_leaf': 64, 'feature_fraction': 0.9422400392941975, 'bagging_fraction': 0.6714179414346618, 'bagging_freq': 4}. Best is trial 6 with value: 0.5024347083825557.
[I 2025-11-08 23:08:24,164] Trial 7 finished with value: 0.5145521848570836 and parameters: {'num_leaves': 59, 'max_depth': 11, 'learning_rate': 0.02540298104884087, 'min_data_in_leaf': 42, 'feature_fraction': 0.8409854165073425, 'bagging_fraction': 0.9024085830300026, 'bagging_freq': 5}. Best is trial 6 with value: 0.5024347083825557.
[I 2025-11-08 23:08:26,365] Trial 8 finished with value: 0.5034436790996926 and parameters: {'num_leaves': 84, 'max_depth': 12, 'learning_rate': 0.16769818791463945, 'min_data_in_leaf': 20, 'feature_fraction': 0.6479432418348545, 'bagging_fraction': 0.9233437539030889, 'bagging_freq': 1}. Best is trial 6 with value: 0.5024347083825557.
[I 2025-11-08 23:08:28,618] Trial 9 finished with value: 0.5016199377240803 and parameters: {'num_leaves': 52, 'max_depth': 11, 'learning_rate': 0.08522883172379585, 'min_data_in_leaf': 86, 'feature_fraction': 0.8641026867992918, 'bagging_fraction': 0.8450010567373951, 'bagging_freq': 3}. Best is trial 9 with value: 0.5016199377240803.
[I 2025-11-08 23:08:30,498] Trial 10 finished with value: 0.5057503154148699 and parameters: {'num_leaves': 20, 'max_depth': 8, 'learning_rate': 0.07927566424905114, 'min_data_in_leaf': 80, 'feature_fraction': 0.7553970732376465, 'bagging_fraction': 0.8161493614994458, 'bagging_freq': 2}. Best is trial 9 with value: 0.5016199377240803.
[I 2025-11-08 23:08:32,354] Trial 11 finished with value: 0.5045669304446487 and parameters: {'num_leaves': 20, 'max_depth': 10, 'learning_rate': 0.0979141849571003, 'min_data_in_leaf': 74, 'feature_fraction': 0.9569309955259173, 'bagging_fraction': 0.6129300167116518, 'bagging_freq': 4}. Best is trial 9 with value: 0.5016199377240803.
[I 2025-11-08 23:08:34,398] Trial 12 finished with value: 0.5011277723814125 and parameters: {'num_leaves': 43, 'max_depth': 7, 'learning_rate': 0.11246548272095329, 'min_data_in_leaf': 69, 'feature_fraction': 0.913797323338134, 'bagging_fraction': 0.8177666069465618, 'bagging_freq': 5}. Best is trial 12 with value: 0.5011277723814125.
[I 2025-11-08 23:08:36,425] Trial 13 finished with value: 0.5023439974921177 and parameters: {'num_leaves': 60, 'max_depth': 6, 'learning_rate': 0.0980881675195414, 'min_data_in_leaf': 81, 'feature_fraction': 0.9001708343906414, 'bagging_fraction': 0.8117131583853906, 'bagging_freq': 5}. Best is trial 12 with value: 0.5011277723814125.
[I 2025-11-08 23:08:38,845] Trial 14 finished with value: 0.5037691794025166 and parameters: {'num_leaves': 72, 'max_depth': 7, 'learning_rate': 0.048402530664705054, 'min_data_in_leaf': 67, 'feature_fraction': 0.7940897986065942, 'bagging_fraction': 0.984404180618968, 'bagging_freq': 2}. Best is trial 12 with value: 0.5011277723814125.
[I 2025-11-08 23:08:41,125] Trial 15 finished with value: 0.5482255649346813 and parameters: {'num_leaves': 49, 'max_depth': 7, 'learning_rate': 0.014963774103702955, 'min_data_in_leaf': 89, 'feature_fraction': 0.8042886219897765, 'bagging_fraction': 0.8490899660345864, 'bagging_freq': 5}. Best is trial 12 with value: 0.5011277723814125.
[I 2025-11-08 23:08:43,375] Trial 16 finished with value: 0.500952288492379 and parameters: {'num_leaves': 71, 'max_depth': 8, 'learning_rate': 0.10641233785684628, 'min_data_in_leaf': 54, 'feature_fraction': 0.9163083535566978, 'bagging_fraction': 0.7578621904658616, 'bagging_freq': 3}. Best is trial 16 with value: 0.500952288492379.
[I 2025-11-08 23:08:45,724] Trial 17 finished with value: 0.5001542101234866 and parameters: {'num_leaves': 99, 'max_depth': 8, 'learning_rate': 0.12392844149984927, 'min_data_in_leaf': 52, 'feature_fraction': 0.9184769031252074, 'bagging_fraction': 0.7693752454819773, 'bagging_freq': 2}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:08:48,195] Trial 18 finished with value: 0.5007879298413821 and parameters: {'num_leaves': 102, 'max_depth': 9, 'learning_rate': 0.1253050248889826, 'min_data_in_leaf': 53, 'feature_fraction': 0.9986520943637334, 'bagging_fraction': 0.7513282170784406, 'bagging_freq': 2}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:08:50,547] Trial 19 finished with value: 0.5055066480073706 and parameters: {'num_leaves': 104, 'max_depth': 9, 'learning_rate': 0.19517874064708926, 'min_data_in_leaf': 44, 'feature_fraction': 0.9719461020587958, 'bagging_fraction': 0.6514974911513611, 'bagging_freq': 2}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:08:53,382] Trial 20 finished with value: 0.5698847078109514 and parameters: {'num_leaves': 96, 'max_depth': 9, 'learning_rate': 0.010156093816454053, 'min_data_in_leaf': 34, 'feature_fraction': 0.9903030365189778, 'bagging_fraction': 0.7668010915122415, 'bagging_freq': 1}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:08:55,749] Trial 21 finished with value: 0.5015695581844974 and parameters: {'num_leaves': 128, 'max_depth': 8, 'learning_rate': 0.1326681653499972, 'min_data_in_leaf': 55, 'feature_fraction': 0.9142138590476089, 'bagging_fraction': 0.7694139642787741, 'bagging_freq': 3}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:08:57,808] Trial 22 finished with value: 0.5031804603120827 and parameters: {'num_leaves': 93, 'max_depth': 6, 'learning_rate': 0.0662754428229449, 'min_data_in_leaf': 54, 'feature_fraction': 0.9277629010065969, 'bagging_fraction': 0.7213475552196233, 'bagging_freq': 2}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:09:00,104] Trial 23 finished with value: 0.501045465829302 and parameters: {'num_leaves': 81, 'max_depth': 8, 'learning_rate': 0.12347504342931864, 'min_data_in_leaf': 58, 'feature_fraction': 0.9946417230898863, 'bagging_fraction': 0.7578154977849118, 'bagging_freq': 3}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:09:02,572] Trial 24 finished with value: 0.5017155708590731 and parameters: {'num_leaves': 72, 'max_depth': 10, 'learning_rate': 0.06438663504698951, 'min_data_in_leaf': 48, 'feature_fraction': 0.9513924856443197, 'bagging_fraction': 0.7859359756198725, 'bagging_freq': 2}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:09:04,667] Trial 25 finished with value: 0.5067878492139486 and parameters: {'num_leaves': 95, 'max_depth': 6, 'learning_rate': 0.04280186833055328, 'min_data_in_leaf': 34, 'feature_fraction': 0.8251104795256895, 'bagging_fraction': 0.7265611315989834, 'bagging_freq': 1}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:09:07,074] Trial 26 finished with value: 0.5018451643490682 and parameters: {'num_leaves': 112, 'max_depth': 9, 'learning_rate': 0.12585397605271534, 'min_data_in_leaf': 50, 'feature_fraction': 0.8917269382361944, 'bagging_fraction': 0.6792242947142414, 'bagging_freq': 2}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:09:09,260] Trial 27 finished with value: 0.5033407249563217 and parameters: {'num_leaves': 101, 'max_depth': 8, 'learning_rate': 0.19982817830251723, 'min_data_in_leaf': 63, 'feature_fraction': 0.7341883300241285, 'bagging_fraction': 0.7900558905823681, 'bagging_freq': 3}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:09:11,517] Trial 28 finished with value: 0.5011857385352666 and parameters: {'num_leaves': 120, 'max_depth': 7, 'learning_rate': 0.07924251468199978, 'min_data_in_leaf': 35, 'feature_fraction': 0.9669238328911312, 'bagging_fraction': 0.6297625124010878, 'bagging_freq': 2}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:09:13,460] Trial 29 finished with value: 0.5132336972473498 and parameters: {'num_leaves': 78, 'max_depth': 5, 'learning_rate': 0.033823692600674436, 'min_data_in_leaf': 72, 'feature_fraction': 0.8832289851911187, 'bagging_fraction': 0.6996892181448893, 'bagging_freq': 1}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:09:15,151] Trial 30 finished with value: 0.5108443752305384 and parameters: {'num_leaves': 89, 'max_depth': 3, 'learning_rate': 0.10508590592422495, 'min_data_in_leaf': 60, 'feature_fraction': 0.9360189802097416, 'bagging_fraction': 0.8336200889846304, 'bagging_freq': 3}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:09:17,432] Trial 31 finished with value: 0.5011256387056685 and parameters: {'num_leaves': 79, 'max_depth': 8, 'learning_rate': 0.1300130776936065, 'min_data_in_leaf': 58, 'feature_fraction': 0.9979323042140498, 'bagging_fraction': 0.7561446152370518, 'bagging_freq': 3}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:09:19,683] Trial 32 finished with value: 0.5014925060207249 and parameters: {'num_leaves': 67, 'max_depth': 9, 'learning_rate': 0.1457057066360398, 'min_data_in_leaf': 49, 'feature_fraction': 0.998265182235099, 'bagging_fraction': 0.7369096944277393, 'bagging_freq': 3}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:09:22,040] Trial 33 finished with value: 0.5014023352563457 and parameters: {'num_leaves': 88, 'max_depth': 8, 'learning_rate': 0.1152743367895386, 'min_data_in_leaf': 59, 'feature_fraction': 0.9628841926150336, 'bagging_fraction': 0.7783822849532688, 'bagging_freq': 4}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:09:24,504] Trial 34 finished with value: 0.502029666305753 and parameters: {'num_leaves': 82, 'max_depth': 10, 'learning_rate': 0.055147464846613085, 'min_data_in_leaf': 52, 'feature_fraction': 0.9243830940483291, 'bagging_fraction': 0.7072144863135065, 'bagging_freq': 2}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:09:26,680] Trial 35 finished with value: 0.5022064286199216 and parameters: {'num_leaves': 66, 'max_depth': 8, 'learning_rate': 0.16161539247068873, 'min_data_in_leaf': 46, 'feature_fraction': 0.9760506584155649, 'bagging_fraction': 0.746887008194926, 'bagging_freq': 3}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:09:29,204] Trial 36 finished with value: 0.5002144435201495 and parameters: {'num_leaves': 104, 'max_depth': 9, 'learning_rate': 0.0893384061283909, 'min_data_in_leaf': 40, 'feature_fraction': 0.8430325428705794, 'bagging_fraction': 0.8711995094572893, 'bagging_freq': 4}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:09:31,762] Trial 37 finished with value: 0.5002034098088476 and parameters: {'num_leaves': 103, 'max_depth': 9, 'learning_rate': 0.0885031029214066, 'min_data_in_leaf': 38, 'feature_fraction': 0.8525074959762984, 'bagging_fraction': 0.8726437848278719, 'bagging_freq': 4}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:09:34,391] Trial 38 finished with value: 0.5003803633524133 and parameters: {'num_leaves': 109, 'max_depth': 11, 'learning_rate': 0.08673602535336851, 'min_data_in_leaf': 38, 'feature_fraction': 0.8367958849347503, 'bagging_fraction': 0.8587896593178885, 'bagging_freq': 4}. Best is trial 17 with value: 0.5001542101234866.
[I 2025-11-08 23:09:37,191] Trial 39 finished with value: 0.5001395591918073 and parameters: {'num_leaves': 120, 'max_depth': 11, 'learning_rate': 0.07186570602178526, 'min_data_in_leaf': 38, 'feature_fraction': 0.8501164053103122, 'bagging_fraction': 0.8735623402886086, 'bagging_freq': 4}. Best is trial 39 with value: 0.5001395591918073.
[I 2025-11-08 23:09:39,968] Trial 40 finished with value: 0.5005819398268138 and parameters: {'num_leaves': 121, 'max_depth': 12, 'learning_rate': 0.06934168370266738, 'min_data_in_leaf': 29, 'feature_fraction': 0.7799170641773534, 'bagging_fraction': 0.8793500272083669, 'bagging_freq': 4}. Best is trial 39 with value: 0.5001395591918073.
[I 2025-11-08 23:09:42,628] Trial 41 finished with value: 0.5006980990318607 and parameters: {'num_leaves': 114, 'max_depth': 11, 'learning_rate': 0.08559227589174569, 'min_data_in_leaf': 38, 'feature_fraction': 0.8357055084381327, 'bagging_fraction': 0.8687739812283235, 'bagging_freq': 4}. Best is trial 39 with value: 0.5001395591918073.
[I 2025-11-08 23:09:45,459] Trial 42 finished with value: 0.5019255723425257 and parameters: {'num_leaves': 107, 'max_depth': 11, 'learning_rate': 0.05461537884692225, 'min_data_in_leaf': 40, 'feature_fraction': 0.8581865845078129, 'bagging_fraction': 0.9134710048625521, 'bagging_freq': 4}. Best is trial 39 with value: 0.5001395591918073.
[I 2025-11-08 23:09:48,191] Trial 43 finished with value: 0.4996198897773192 and parameters: {'num_leaves': 126, 'max_depth': 10, 'learning_rate': 0.08978818170586202, 'min_data_in_leaf': 29, 'feature_fraction': 0.8203934438798848, 'bagging_fraction': 0.9388034565301653, 'bagging_freq': 4}. Best is trial 43 with value: 0.4996198897773192.
[I 2025-11-08 23:09:50,955] Trial 44 finished with value: 0.5002129070987616 and parameters: {'num_leaves': 123, 'max_depth': 10, 'learning_rate': 0.07290573114784643, 'min_data_in_leaf': 29, 'feature_fraction': 0.8126207037806751, 'bagging_fraction': 0.9357065738249096, 'bagging_freq': 4}. Best is trial 43 with value: 0.4996198897773192.
[I 2025-11-08 23:09:53,901] Trial 45 finished with value: 0.5050018299857736 and parameters: {'num_leaves': 125, 'max_depth': 10, 'learning_rate': 0.036061869628002376, 'min_data_in_leaf': 26, 'feature_fraction': 0.8119639099733047, 'bagging_fraction': 0.9528790382542693, 'bagging_freq': 5}. Best is trial 43 with value: 0.4996198897773192.
[I 2025-11-08 23:09:56,726] Trial 46 finished with value: 0.5003050987722041 and parameters: {'num_leaves': 117, 'max_depth': 10, 'learning_rate': 0.07436256555113883, 'min_data_in_leaf': 23, 'feature_fraction': 0.8651411298622211, 'bagging_fraction': 0.9517042994746814, 'bagging_freq': 4}. Best is trial 43 with value: 0.4996198897773192.
[I 2025-11-08 23:09:59,570] Trial 47 finished with value: 0.5016238070492527 and parameters: {'num_leaves': 123, 'max_depth': 12, 'learning_rate': 0.05763026207534254, 'min_data_in_leaf': 30, 'feature_fraction': 0.7652576812725076, 'bagging_fraction': 0.8953604589791733, 'bagging_freq': 4}. Best is trial 43 with value: 0.4996198897773192.
[I 2025-11-08 23:10:02,335] Trial 48 finished with value: 0.5034607155860321 and parameters: {'num_leaves': 115, 'max_depth': 11, 'learning_rate': 0.047712962537629175, 'min_data_in_leaf': 20, 'feature_fraction': 0.6921179618287213, 'bagging_fraction': 0.9441654983164552, 'bagging_freq': 5}. Best is trial 43 with value: 0.4996198897773192.
[I 2025-11-08 23:10:04,955] Trial 49 finished with value: 0.5008364236432499 and parameters: {'num_leaves': 126, 'max_depth': 10, 'learning_rate': 0.09020579211775544, 'min_data_in_leaf': 31, 'feature_fraction': 0.601683813426467, 'bagging_fraction': 0.9835771093049169, 'bagging_freq': 4}. Best is trial 43 with value: 0.4996198897773192.
[I 2025-11-08 23:10:07,766] Trial 50 finished with value: 0.5005241800720064 and parameters: {'num_leaves': 120, 'max_depth': 10, 'learning_rate': 0.071125719491362, 'min_data_in_leaf': 44, 'feature_fraction': 0.815854673746606, 'bagging_fraction': 0.974787677242199, 'bagging_freq': 5}. Best is trial 43 with value: 0.4996198897773192.
[I 2025-11-08 23:10:10,334] Trial 51 finished with value: 0.5003031885745699 and parameters: {'num_leaves': 108, 'max_depth': 9, 'learning_rate': 0.09657184464475628, 'min_data_in_leaf': 26, 'feature_fraction': 0.8489538860577205, 'bagging_fraction': 0.8916074033903478, 'bagging_freq': 4}. Best is trial 43 with value: 0.4996198897773192.
[I 2025-11-08 23:10:12,908] Trial 52 finished with value: 0.5007850388455225 and parameters: {'num_leaves': 100, 'max_depth': 9, 'learning_rate': 0.07476836486674938, 'min_data_in_leaf': 37, 'feature_fraction': 0.7855035176217441, 'bagging_fraction': 0.9260392066542048, 'bagging_freq': 4}. Best is trial 43 with value: 0.4996198897773192.
[I 2025-11-08 23:10:15,626] Trial 53 finished with value: 0.5005035308856666 and parameters: {'num_leaves': 110, 'max_depth': 11, 'learning_rate': 0.09452897259957377, 'min_data_in_leaf': 42, 'feature_fraction': 0.8724195848158134, 'bagging_fraction': 0.9106502314166233, 'bagging_freq': 4}. Best is trial 43 with value: 0.4996198897773192.
[I 2025-11-08 23:10:18,106] Trial 54 finished with value: 0.5013125879760528 and parameters: {'num_leaves': 105, 'max_depth': 9, 'learning_rate': 0.10288673611245415, 'min_data_in_leaf': 32, 'feature_fraction': 0.8278836208218178, 'bagging_fraction': 0.8276714379182458, 'bagging_freq': 4}. Best is trial 43 with value: 0.4996198897773192.
[I 2025-11-08 23:10:20,688] Trial 55 finished with value: 0.5015069273147031 and parameters: {'num_leaves': 117, 'max_depth': 10, 'learning_rate': 0.1489246512329324, 'min_data_in_leaf': 98, 'feature_fraction': 0.9007109415332704, 'bagging_fraction': 0.8724753027326305, 'bagging_freq': 5}. Best is trial 43 with value: 0.4996198897773192.
[I 2025-11-08 23:10:23,499] Trial 56 finished with value: 0.5012296010392087 and parameters: {'num_leaves': 99, 'max_depth': 12, 'learning_rate': 0.0634224142813175, 'min_data_in_leaf': 24, 'feature_fraction': 0.8510126474201418, 'bagging_fraction': 0.9648140743575866, 'bagging_freq': 4}. Best is trial 43 with value: 0.4996198897773192.
[I 2025-11-08 23:10:26,152] Trial 57 finished with value: 0.5001562388716116 and parameters: {'num_leaves': 122, 'max_depth': 10, 'learning_rate': 0.07918289994916729, 'min_data_in_leaf': 40, 'feature_fraction': 0.7982243852860756, 'bagging_fraction': 0.8047676034623709, 'bagging_freq': 5}. Best is trial 43 with value: 0.4996198897773192.

In [136]:

final_model = LGBMRegressor(
    **study.best_params, 
    verbose = 1
)
# Обучаем нашу модель на подобранных парамтов
final_model.fit(
    pd.concat([X_train, X_valid], ignore_index = True),
    pd.concat([y_train, y_valid], ignore_index = True)
)

y_pred = final_model.predict(X_test)

[LightGBM] [Warning] feature_fraction is set=0.9583476523590113, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9583476523590113
[LightGBM] [Warning] min_data_in_leaf is set=46, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=46
[LightGBM] [Warning] bagging_fraction is set=0.943548491093609, subsample=1.0 will be ignored. Current value: bagging_fraction=0.943548491093609
[LightGBM] [Warning] bagging_freq is set=1, subsample_freq=0 will be ignored. Current value: bagging_freq=1
[LightGBM] [Warning] feature_fraction is set=0.9583476523590113, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9583476523590113
[LightGBM] [Warning] min_data_in_leaf is set=46, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=46
[LightGBM] [Warning] bagging_fraction is set=0.943548491093609, subsample=1.0 will be ignored. Current value: bagging_fraction=0.943548491093609
[LightGBM] [Warning] bagging_freq is set=1, subsample_freq=0 will be ignored. Current value: bagging_freq=1
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.026454 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 37547
[LightGBM] [Info] Number of data points in the train set: 184014, number of used features: 170
[LightGBM] [Info] Start training from score 5.607615
[LightGBM] [Warning] feature_fraction is set=0.9583476523590113, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9583476523590113
[LightGBM] [Warning] min_data_in_leaf is set=46, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=46
[LightGBM] [Warning] bagging_fraction is set=0.943548491093609, subsample=1.0 will be ignored. Current value: bagging_fraction=0.943548491093609
[LightGBM] [Warning] bagging_freq is set=1, subsample_freq=0 will be ignored. Current value: bagging_freq=1

In [2]:
mae = mean_absolute_error(y_test, y_pred)
print(f"MAE: {mae:.4f}  Score: {1 / (1 + mae):.4f}") # Проверяем, какой бы примерный балл нам бы вернула система.

MAE: 0.5114  Score: 0.6616